import {
  SalesReportProductRpcReturn,
  SalesReportSummaryRpcReturn,
} from '../../../../../app/sales/interface/sales-report.interface';
import { buildHtmlDocument } from '../../html/html-builder';
import { DataQueryResponse } from '../../../../../@types/general';
import { SalesItemApiResponse } from '../../../../../app/sales/interface/sales-items.interface';

interface SalesReportPdfData {
  summary: SalesReportSummaryRpcReturn;
  fullDetail: DataQueryResponse<SalesItemApiResponse[]>;
  productSummary: DataQueryResponse<SalesReportProductRpcReturn[]>;
  categoryChart: { category: string; omzet: number }[];
}

export function buildHtml({
  summary,
  fullDetail,
  productSummary,
  categoryChart,
}: SalesReportPdfData) {
  const summarySection = buildSummarySection(summary);
  const fullDetailSection = buildFullDetailSection(fullDetail);
  const productSummarySection = buildProductSummarySection(productSummary);
  const categoryChartSection = buildCategoryPieChartSection(categoryChart);

  const html = buildHtmlDocument({
    title: 'Laporan Penjualan',
    tailwind: true,
    body: `
      <div class="bg-gray-100 min-h-screen py-10">
        <div class="max-w-4xl mx-auto bg-white px-10 py-8 text-gray-800">

          <!-- Header -->
          <header class="border-b pb-6 mb-8">
            <div class="flex justify-between items-start">
              <div>
                <h1 class="text-2xl font-bold">
                  Laporan Penjualan
                </h1>
                <p class="mt-1 text-sm text-gray-500">
                  Ringkasan transaksi penjualan
                </p>
              </div>

              <div class="text-right text-sm leading-5">
                <p class="font-medium">Toserba Aqil</p>
                <p class="text-gray-500">
                  Dicetak: ${new Date().toLocaleDateString('id-ID')}
                </p>
              </div>
            </div>
          </header>

          <!-- Content -->
          <main class="min-h-[400px]">
            ${summarySection}

            <div class="page-break mb-8"></div>
            
            ${fullDetailSection}
            
            <div class="page-break mb-8"></div>
            ${productSummarySection}
            
            <div class="page-break mb-8"></div>
            ${categoryChartSection}
          </main>

          <!-- Footer -->
          <footer class="border-t pt-4 mt-10 text-sm text-gray-500 flex justify-between">
            <span>
              © ${new Date().getFullYear()} Toserba Aqil
            </span>
            <span>
              Generated by System
            </span>
          </footer>

        </div>
      </div>
    `,
  });

  return html;
}

const formatRupiah = (value: number) =>
  `Rp ${value.toLocaleString('id-ID', { maximumFractionDigits: 0 })}`;
const formatPercent = (value: number) => `${value.toFixed(1)}%`;

const buildSummarySection = (data: SalesReportSummaryRpcReturn) => {
  return `
    <section class="mb-10">
      <h2 class="text-lg font-semibold mb-4">
        Ringkasan Penjualan
      </h2>

      <div class="grid grid-cols-2 gap-4 text-sm">

        <div class="border rounded p-4">
          <p class="text-gray-500">Omzet</p>
          <p class="mt-1 text-xl font-bold">
            ${formatRupiah(data.omzet)}
          </p>
        </div>

        <div class="border rounded p-4">
          <p class="text-gray-500">Total Transaksi</p>
          <p class="mt-1 text-xl font-bold">
            ${data.total_transaction} Transaksi
          </p>
        </div>

        <div class="border rounded p-4">
          <p class="text-gray-500">HPP</p>
          <p class="mt-1 text-xl font-bold text-red-600">
            ${formatRupiah(data.hpp)}
          </p>
        </div>

        <div class="border rounded p-4">
          <p class="text-gray-500">Margin</p>
          <p class="mt-1 text-xl font-bold text-green-600">
            ${formatRupiah(data.omzet - data.hpp)}
          </p>
        </div>

        <div class="border rounded p-4">
          <p class="text-gray-500">Margin (%)</p>
          <p class="mt-1 text-xl font-bold">
            ${(data.margin_percent * 100).toFixed(2)}%
          </p>
        </div>

        <div class="border rounded p-4">
          <p class="text-gray-500">Markup (%)</p>
          <p class="mt-1 text-xl font-bold">
            ${(data.markup_percent * 100).toFixed(2)}%
          </p>
        </div>

      </div>
    </section>
  `;
};

const buildFullDetailSection = (
  response: DataQueryResponse<SalesItemApiResponse[]>,
) => {
  const { data, meta } = response;

  const rows = data
    .map(
      (item, index) => `
      <tr class="border-b">
        <td class="py-2 px-3 text-center">
          ${index + 1}
        </td>
        <td class="py-2 px-3">
          ${item.sales_id?.customer_name ?? '-'}
        </td>
        <td class="py-2 px-3 text-right">
          ${item.quantity}
        </td>
        <td class="py-2 px-3 text-right">
          ${formatRupiah(item.subtotal)}
        </td>
      </tr>
    `,
    )
    .join('');

  return `
    <section class="mb-10">
      <h2 class="text-lg font-semibold mb-2">
        Detail Penjualan
      </h2>

      <p class="text-sm text-gray-500 mb-4">
        Menampilkan ${data.length} dari ${meta.total} transaksi
      </p>

      <div class="overflow-x-auto">
        <table class="w-full border-collapse text-sm">
          <thead class="table-header-group">
            <tr class="border-b bg-gray-50">
              <th class="py-2 px-3 text-center w-10">No</th>
              <th class="py-2 px-3 text-left">Pembeli</th>
              <th class="py-2 px-3 text-right">Qty</th>
              <th class="py-2 px-3 text-right">Subtotal</th>
            </tr>
          </thead>
          <tbody>
            ${
              rows ||
              `
              <tr>
                <td colspan="6" class="py-6 text-center text-gray-500">
                  Tidak ada data
                </td>
              </tr>
            `
            }
          </tbody>
        </table>
      </div>
    </section>
  `;
};

const buildProductSummarySection = (
  response: DataQueryResponse<SalesReportProductRpcReturn[]>,
) => {
  const { data, meta } = response;

  const rows = data
    .map(
      (item, index) => `
        <tr class="border-b">
          <td class="py-2 px-3 text-center">
            ${index + 1}
          </td>
          <td class="py-2 px-3">
            ${item.product_name}
          </td>
          <td class="py-2 px-3 text-right">
            ${item.quantity}
          </td>
          <td class="py-2 px-3 text-right">
            ${formatRupiah(item.subtotal)}
          </td>
        </tr>
      `,
    )
    .join('');

  return `
    <section class="mb-10">
      <h2 class="text-lg font-semibold mb-2">
        Ringkasan Penjualan per Produk
      </h2>

      <p class="text-sm text-gray-500 mb-4">
        Menampilkan ${data.length} dari ${meta.total} produk
      </p>

      <div class="overflow-x-auto">
        <table class="w-full border-collapse text-sm">
          <thead>
            <tr class="border-b bg-gray-50">
              <th class="py-2 px-3 text-center w-10">No</th>
              <th class="py-2 px-3 text-left">Produk</th>
              <th class="py-2 px-3 text-right">Qty</th>
              <th class="py-2 px-3 text-right">Subtotal</th>
            </tr>
          </thead>
          <tbody>
            ${
              rows ||
              `
              <tr>
                <td colspan="8" class="py-6 text-center text-gray-500">
                  Tidak ada data
                </td>
              </tr>
            `
            }
          </tbody>
        </table>
      </div>
    </section>
  `;
};

const buildCategoryInsight = (data: { category: string; omzet: number }[]) => {
  if (!data.length) return '';

  const totalOmzet = data.reduce((sum, i) => sum + i.omzet, 0);

  const sorted = [...data].sort((a, b) => b.omzet - a.omzet);

  const largest = sorted[0];
  const smallest = sorted[sorted.length - 1];

  const largestPercent = (largest.omzet / totalOmzet) * 100;

  const dependencyInsight =
    largestPercent >= 70
      ? `⚠️ Ketergantungan terhadap kategori <strong>${largest.category}</strong> cukup tinggi (${formatPercent(
          largestPercent,
        )} dari total omzet). Perlu dipertimbangkan strategi diversifikasi penjualan.`
      : `Distribusi omzet cukup seimbang antar kategori.`;

  return `
    <div class="mt-6 text-sm space-y-2">
      <p>
        Distribusi omzet menunjukkan bahwa kategori
        <strong>${largest.category}</strong>
        memberikan kontribusi terbesar terhadap total penjualan.
      </p>

      <ul class="list-disc pl-5">
        <li>
          🥇 Kategori terbesar:
          <strong>${largest.category}</strong>
          (${formatRupiah(largest.omzet)} • ${formatPercent(largestPercent)})
        </li>
        <li>
          📊 Total omzet:
          <strong>${formatRupiah(totalOmzet)}</strong>
        </li>
        <li>
          🔻 Kategori terkecil:
          <strong>${smallest.category}</strong>
          (${formatRupiah(smallest.omzet)})
        </li>
      </ul>

      <p class="mt-2">
        ${dependencyInsight}
      </p>
    </div>
  `;
};

const mapCategoryToPieData = (data: { category: string; omzet: number }[]) =>
  data.map((d) => ({
    name: d.category,
    value: d.omzet,
  }));

const PIE_COLORS = [
  '#0088FE',
  '#00C49F',
  '#FFBB28',
  '#FF8042',
  '#A28BFE',
  '#FF5C8D',
];

const buildCategoryPieChartSection = (
  rawData: { category: string; omzet: number }[],
) => {
  const data = mapCategoryToPieData(rawData);

  const labels = data.map((d) => d.name);
  const values = data.map((d) => d.value);

  const insight = buildCategoryInsight(rawData);

  return `
    <section class="mb-10">
      <h2 class="text-lg font-semibold mb-4">
        Distribusi Omzet per Kategori
      </h2>

      <div class="spaye-y-6 items-center">
        <div class="w-full">
          <canvas id="categoryPieChart"></canvas>
        </div>

        <div>
          ${insight}
        </div>
      </div>

      <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels"></script>

      <script>
        const ctx = document.getElementById('categoryPieChart');

        const dataValues = ${JSON.stringify(values)};
        const total = dataValues.reduce((a, b) => a + b, 0);

        new Chart(ctx, {
          type: 'pie',
          data: {
            labels: ${JSON.stringify(labels)},
            datasets: [{
              data: dataValues,
              backgroundColor: ${JSON.stringify(PIE_COLORS)},
            }]
          },
          options: {
            responsive: true,
            aspectRatio: 3,
            plugins: {
              legend: {
                position: 'bottom',
              },
              tooltip: {
                callbacks: {
                  label: function(ctx) {
                    const value = ctx.raw;
                    return 'Rp ' + value.toLocaleString('id-ID');
                  }
                }
              },
              datalabels: {
                color: '#333',
                font: {
                  size: 11,
                  weight: 'bold',
                },
                formatter: function(value, ctx) {
                  const percent = (value / total) * 100;
                  return ctx.chart.data.labels[ctx.dataIndex] 
                    + ' (' 
                    + percent.toFixed(2) 
                    + '%)';
                }
              }
            }
          },
          plugins: [ChartDataLabels]
        });
      </script>
    </section>
  `;
};
