export enum TableName {
  ACTIVITY_LOGS = 'activity_logs',
  BALANCE_SNAPSHOTS = 'balance_snapshots',
  CASH_COUNT_DETAILS = 'cash_count_details',
  CASH_COUNTS = 'cash_counts',
  CASHFLOW = 'cashflow',
  CASHFLOW_CATEGORY = 'cashflow_category',
  CASHFLOW_UNIQUE_VIA = 'cashflow_unique_via',
  CUSTOMER_NAME = 'customer_name',
  DENOMINATIONS = 'denominations',
  PRODUCTS = 'products',
  PURCHASE_ASSETS = 'purchase_assets',
  PURCHASE_CONSUMABLES = 'purchase_consumables',
  PURCHASE_ITEMS = 'purchase_items',
  PURCHASE_SUPPLIER_NAME = 'purchase_supplier_name',
  PURCHASE_SUPPLIER_TYPE = 'purchase_supplier_type',
  PURCHASES = 'purchases',
  SALES = 'sales',
  SALES_ITEMS = 'sales_items',
  THIRD_PARTY_CASH = 'third_party_cash',
  VENDOR_NAME = 'vendor_name',
}